//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteShopDHND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_prod { get; set; }
        public int id_cate { get; set; }
        public string name_prod { get; set; }
        public string des_prod { get; set; }
        public string img_prod { get; set; }
        public bool status_prod { get; set; }
        public int time_Start { get; set; }
        public int time_Update { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
